// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseLogDir(arg1:string):Promise<string>;

export function CloseTab(arg1:number):Promise<void>;

export function Connect(arg1:number,arg2:main.ConnectRequest):Promise<string>;

export function DebugEnabled():Promise<boolean>;

export function DebugLog(arg1:string):Promise<void>;

export function Disconnect(arg1:number):Promise<void>;

export function FileCancel(arg1:number):Promise<void>;

export function FileClose(arg1:number):Promise<void>;

export function FileDelete(arg1:number,arg2:string,arg3:Array<main.FileEntry>):Promise<number>;

export function FileDownload(arg1:number,arg2:string,arg3:number):Promise<string>;

export function FileDownloadMany(arg1:number,arg2:string,arg3:Array<main.FileEntry>):Promise<main.DownloadResult>;

export function FileList(arg1:number,arg2:string):Promise<Array<main.FileEntry>>;

export function FileMkdir(arg1:number,arg2:string,arg3:string):Promise<void>;

export function FileOpen(arg1:number):Promise<main.FileOpenResult>;

export function FileRename(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FileUpload(arg1:number,arg2:string):Promise<number>;

export function FileUploadPaths(arg1:number,arg2:string,arg3:Array<string>):Promise<number>;

export function FileView(arg1:number,arg2:string,arg3:number):Promise<main.ViewResult>;

export function ForwardAdd(arg1:number,arg2:main.Forward):Promise<main.ForwardStatus>;

export function ForwardList(arg1:number):Promise<Array<main.ForwardStatus>>;

export function ForwardRemove(arg1:number,arg2:number):Promise<void>;

export function GetHistory():Promise<Array<main.HostEntry>>;

export function GetSSHConfigHosts():Promise<Array<main.SSHConfigHost>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function LogPath(arg1:number):Promise<string>;

export function LookupSSH(arg1:string):Promise<main.SSHTarget>;

export function Resize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Send(arg1:number,arg2:string):Promise<void>;

export function SetEncoding(arg1:number,arg2:string):Promise<string>;

export function ShowLogs(arg1:number):Promise<void>;

export function StartLog(arg1:number):Promise<string>;

export function StopLog(arg1:number):Promise<void>;

export function TextSaveAs(arg1:string,arg2:string,arg3:string):Promise<main.SaveResult>;
