// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function FileCancel(arg1) {
  return window['go']['main']['App']['FileCancel'](arg1);
}

export function FileClose(arg1) {
  return window['go']['main']['App']['FileClose'](arg1);
}

export function FileDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDownload'](arg1, arg2, arg3);
}

export function FileList(arg1, arg2) {
  return window['go']['main']['App']['FileList'](arg1, arg2);
}

export function FileOpen(arg1) {
  return window['go']['main']['App']['FileOpen'](arg1);
}

export function FileUpload(arg1, arg2) {
  return window['go']['main']['App']['FileUpload'](arg1, arg2);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Resize'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}

export function SetEncoding(arg1, arg2) {
  return window['go']['main']['App']['SetEncoding'](arg1, arg2);
}
