// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function FileCancel() {
  return window['go']['main']['App']['FileCancel']();
}

export function FileClose() {
  return window['go']['main']['App']['FileClose']();
}

export function FileDownload(arg1, arg2) {
  return window['go']['main']['App']['FileDownload'](arg1, arg2);
}

export function FileList(arg1) {
  return window['go']['main']['App']['FileList'](arg1);
}

export function FileOpen() {
  return window['go']['main']['App']['FileOpen']();
}

export function FileUpload(arg1) {
  return window['go']['main']['App']['FileUpload'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Resize(arg1, arg2) {
  return window['go']['main']['App']['Resize'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SetEncoding(arg1) {
  return window['go']['main']['App']['SetEncoding'](arg1);
}
