// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerPrompt'](arg1, arg2, arg3);
}

export function ChooseLogDir(arg1) {
  return window['go']['main']['App']['ChooseLogDir'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function DebugEnabled() {
  return window['go']['main']['App']['DebugEnabled']();
}

export function DebugLog(arg1) {
  return window['go']['main']['App']['DebugLog'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function FileCancel(arg1) {
  return window['go']['main']['App']['FileCancel'](arg1);
}

export function FileClose(arg1) {
  return window['go']['main']['App']['FileClose'](arg1);
}

export function FileDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDelete'](arg1, arg2, arg3);
}

export function FileDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDownload'](arg1, arg2, arg3);
}

export function FileDownloadMany(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileDownloadMany'](arg1, arg2, arg3);
}

export function FileList(arg1, arg2) {
  return window['go']['main']['App']['FileList'](arg1, arg2);
}

export function FileMkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileMkdir'](arg1, arg2, arg3);
}

export function FileOpen(arg1) {
  return window['go']['main']['App']['FileOpen'](arg1);
}

export function FileRename(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FileRename'](arg1, arg2, arg3, arg4);
}

export function FileSaveText(arg1, arg2) {
  return window['go']['main']['App']['FileSaveText'](arg1, arg2);
}

export function FileStartDir(arg1, arg2) {
  return window['go']['main']['App']['FileStartDir'](arg1, arg2);
}

export function FileUpload(arg1, arg2) {
  return window['go']['main']['App']['FileUpload'](arg1, arg2);
}

export function FileUploadPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileUploadPaths'](arg1, arg2, arg3);
}

export function FileView(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileView'](arg1, arg2, arg3);
}

export function ForwardAdd(arg1, arg2) {
  return window['go']['main']['App']['ForwardAdd'](arg1, arg2);
}

export function ForwardList(arg1) {
  return window['go']['main']['App']['ForwardList'](arg1);
}

export function ForwardRemove(arg1, arg2) {
  return window['go']['main']['App']['ForwardRemove'](arg1, arg2);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSSHConfigHosts() {
  return window['go']['main']['App']['GetSSHConfigHosts']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LogPath(arg1) {
  return window['go']['main']['App']['LogPath'](arg1);
}

export function LookupSSH(arg1) {
  return window['go']['main']['App']['LookupSSH'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Resize'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Send(arg1, arg2) {
  return window['go']['main']['App']['Send'](arg1, arg2);
}

export function SetEncoding(arg1, arg2) {
  return window['go']['main']['App']['SetEncoding'](arg1, arg2);
}

export function ShowLogs(arg1) {
  return window['go']['main']['App']['ShowLogs'](arg1);
}

export function StartLog(arg1) {
  return window['go']['main']['App']['StartLog'](arg1);
}

export function StopLog(arg1) {
  return window['go']['main']['App']['StopLog'](arg1);
}

export function TextSaveAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['TextSaveAs'](arg1, arg2, arg3);
}
