// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTab(arg1:number):Promise<void>;

export function Connect(arg1:number,arg2:main.ConnectRequest):Promise<string>;

export function Disconnect(arg1:number):Promise<void>;

export function FileCancel(arg1:number):Promise<void>;

export function FileClose(arg1:number):Promise<void>;

export function FileDownload(arg1:number,arg2:string,arg3:number):Promise<string>;

export function FileList(arg1:number,arg2:string):Promise<Array<main.FileEntry>>;

export function FileOpen(arg1:number):Promise<main.FileOpenResult>;

export function FileUpload(arg1:number,arg2:string):Promise<number>;

export function GetHistory():Promise<Array<main.HostEntry>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function Resize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Send(arg1:number,arg2:string):Promise<void>;

export function SetEncoding(arg1:number,arg2:string):Promise<string>;
